name: Automated Testing of Interface Availability

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # run on every day 14:00

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hust_login

      - name: Install tesseract
        run: |
          sudo apt install tesseract-ocr -y
      
      - name: Test module
        run: |
          python -m hust_login --autotest -U ${{ secrets.UID }} -P ${{ secrets.PWD }}
          
