name: Automated Testing of Interface Availability

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # run on every day 14:00

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hust_login

      - name: Install MacPorts(Mac)
        if: matrix.os == 'macos-latest'
        uses: melusina-org/gha-install-macports@v1.0.0

      - name: Install tesseract(Mac)
        if: matrix.os == 'macos-latest'
        run: |
          sudo port install tesseract

      - name: Install tesseract(Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install tesseract-ocr -y

      - name: Install tesseract(Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo 'Not available'
      
      - name: Test module
        run: |
          python -m hust_login --autotest -U ${{ secrets.Uid }} -P ${{ secrets.Pwd }}
          
