name: Automated Testing of Interface Availability

on:
  workflow_call:
    inputs:
      name: 
        required: true
        type: string
    secrets:
      Uid:
        required: true
      Pwd:
        required: true
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] #[windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.name }}

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ${{ inputs.name }}
          python -m hust_login --autotest -U ${{ secrets.Uid }} -P ${{ secrets.Pwd }}

      #- name: release
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    files: "dist/**"
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
