name: Automated Testing of Interface Availability

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install build

      - name: Build package
        run: python -m build

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist/*
      
      - name: cleanup artifacts 
        run: rm -r dist 

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] #[windows-latest, macos-latest, ubuntu-latest]

    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hust_login-*.whl
      #    python -m hust_login --autotest -U ${{ secrets.Uid }} -P ${{ secrets.Pwd }}

      #- name: release
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    files: "dist/**"
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
