name: Automated Testing of Interface Availability

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build artifacts
        id: build
        uses: ./.github/workflows/build.yml

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] #[windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          tree && ls -a
      #    pip install ${{ inputs.name }}
      #    python -m hust_login --autotest -U ${{ secrets.Uid }} -P ${{ secrets.Pwd }}

      #- name: release
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    files: "dist/**"
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
